### ISSUE TITLE
Error in first line of correct file

### ISSUE THREAD

**Issue by andrekoehler** [plexsystems/vscode-protolint#16]
"at /go/pkg/mod/github.com/yoheimuta/go-protoparser/v4@v4.2.0/parser/syntax.go:59. Use -v for more details"

![Screenshot (92)](https://user-images.githubusercontent.com/22099714/100451523-dc69c600-30b7-11eb-9099-d19c7cae3806.png)

protolint version 0.26.1(84c57fd)

OS Name	Microsoft Windows 10 Pro
Version	10.0.19042 Build 19042

proto file:
```
syntax = "proto3";
package SaM.Projection.Proto;

service projectionService
{
  rpc GetApplicationMode(GetApplicationModeRequest) returns (GetApplicationModeResponse);
}

enum ApplicationMode
{
  APPLICATION_MODE_UNSPECIFIED = 0;
  APPLICATION_MODE_CALIBRATION = 1;
  APPLICATION_MODE_CHECK_CALIBRATION_MAT_POINTS = 2;
  APPLICATION_MODE_DEFINE_VISIBLE_RECTANGLE = 3;
}

message GetApplicationModeRequest
{
}
message GetApplicationModeResponse
{
  ApplicationMode application_mode = 1;
}

```

**Comment by jpreese** [comment]
I am not able to reproduce this at the moment, and given the age of the ticket could have been an issue with a previous version of `protolint`.

If this is still an issue, please feel free to re-open this!
