### ISSUE TITLE
Errors not appearing in problems window (extension not working)

### ISSUE THREAD

**Issue by chrisdMSFT** [plexsystems/vscode-protolint#19]
Testing with your examples and I get the error from protolint but no love with the extension.

![image](https://user-images.githubusercontent.com/73906532/119404840-3c22e180-bc95-11eb-8d4c-d5a51637f052.png)

```
PS G:\vscode-protolint\example> protolint version
protolint version 0.31.0(d193089)
```
Windows 10, vscode 1.56.2, extensions in screen shot.

I'm also not sure what extension for proto syntax highlighting extension you recommend and/or test with.

**Comment by jpreese** [comment]
@chrisdMSFT sorry for the delay, thanks for reporting this! I've personally been using [vscode-proto3](https://marketplace.visualstudio.com/items?itemName=zxh404.vscode-proto3).

For the issue at hand, after some digging, it looks to be that the extension can't find the `.protolint.yaml` because it's inside of the `examples` folder, but the workspace is going to be `vscode-protolint`. The problem exists if your current workspace does not contain a `.protolint.yaml` file

To fix, as a sanity check, you could open the `examples` folder explicitly inside of VSCode and it should work for you.

I'm thinking through a better way to approach config resolution and the potential for multiple workspaces. At a minimum some error logging wouldn't hurt in this case. 😄

**Comment by chrisdMSFT** [comment]
Thanks. It's working now, however it's only showing the problems when I open and then save (Ctrl+S) the file, and only for that file. (Not sure if this is expected).

Repro (with pictures):

Open bar.proto and saved it.
![image](https://user-images.githubusercontent.com/73906532/120526833-83445d00-c38e-11eb-8705-09a155e99be0.png)

Open baz - Note the problem is still only for bar. 

![image](https://user-images.githubusercontent.com/73906532/120526881-92c3a600-c38e-11eb-958e-56cbc4b5f146.png)

Ctrl+S (safe) on baz_with_whitespace.proto
![image](https://user-images.githubusercontent.com/73906532/120526984-ad961a80-c38e-11eb-9143-3ba4f3a9256a.png)

We now detect and highlight the issue but the previous issue is cleared.

**Comment by jpreese** [comment]
@chrisdMSFT I had noticed this as well as I was testing everything. I've added an event for opening protos as well which I'll include in the 0.6.0 release coming up here shortly

https://github.com/plexsystems/vscode-protolint/blob/master/src/extension.ts#L19

**Comment by jpreese** [comment]
v0.6.0 has been released which should make it a bit easier to diagnose errors and immediately lint when moving to a new file.

**Comment by chrisdMSFT** [comment]
Oh I saw the popup telling me"

"protolint was not detected. Download from: https://github.com/yoheimuta/protolint" 

But protolint.exe is on the path confirmed before I started vs code and in the terminal.

![image](https://user-images.githubusercontent.com/73906532/121248053-ceabaf00-c857-11eb-9aee-c7d711b429ab.png)

Should I open a new issue against 0.6.0?

**Comment by jpreese** [comment]
Sorry about the trouble, @chrisdMSFT. I have a Windows machine here that I can try the extension against. It may be related to this section here about `ENV` and Windows: https://nodejs.org/api/child_process.html#child_process_child_process

Any information you gather is greatly appreciated, and I'll do some investigation on my end as well.

**Comment by jpreese** [comment]
I just tried on my Windows machine and the extension is working on this end. I only have `PATH` set when using `printenv` (i.e. Path is unset).

Do you potentially have two versions of protolint installed? One on the path and one not? Maybe your PATH length has grown too big and is being truncated?

**Comment by jpreese** [comment]
Awesome to hear! It should hopefully lint if you _switch_ to the file. I didn't add an event for an initial load, but could do that.
