### ISSUE TITLE
User path to protolint

### ISSUE THREAD

**Issue by aulMasa** [plexsystems/vscode-protolint#25]
Is it possible to add a user path to the protolint binary instead of $PATH ?

**Comment by jpreese** [comment]
@aulMasa for clarity, you're asking for a setting within the extension to be able to set where to look for protolint? 

e.g. `setting.path = /Users/name/bin/protolint` where `/Users/name/bin` is not in `$PATH`

**Comment by aulMasa** [comment]
yes

**Comment by jpreese** [comment]
@aulMasa this has been released as part of `0.7.0`
