### ISSUE TITLE
Update 0.8.0 wasn't published to Visual Studio Marketplace

### ISSUE THREAD

**Issue by AlexCannonball** [plexsystems/vscode-protolint#33]
Hello, here's the issue:
https://github.com/plexsystems/vscode-protolint/actions/runs/4569122585
> You're using an expired Personal Access Token, please get a new PAT.

And I see the latest version `0.7.0` in the Visual Studio Marketplace indeed.

**Comment by jpreese** [comment]
This has been completed via https://github.com/plexsystems/vscode-protolint/issues/35
