### ISSUE TITLE
.protolint.yaml can't affect vscode-protolint

### ISSUE THREAD

**Issue by MartinChangCF** [plexsystems/vscode-protolint#9]
As the title and my version info are as follows
- vscode version: 1.43.0
- vscode-protolint version: 0.2.0
- protolint version: v0.23.2
- go version: go1.14 (and using gvm)

### My proto
![image](https://user-images.githubusercontent.com/25523621/76282784-b6a35380-62d3-11ea-87b1-108fb2a67dae.png)

### My .protolint.yaml
![image](https://user-images.githubusercontent.com/25523621/76282808-d33f8b80-62d3-11ea-9726-240b370ef9ce.png)

### My file structure

```text
- root
  - definition
    - myproto.proto
  - .protolint.yaml
```

and also tried

```text
- root
  - definition
    - myproto.proto
    - .protolint.yaml
```

Just wondering why the .protolint.yaml didn't affect vscode linting as expected.

**Comment by jpreese** [comment]
Thanks for submitting the issue @MartinChangCF! I will be looking into this today. 

In the meantime, have you tested your configuration with just `protolint` on the command line? I'd like to rule out a `protolint` specific issue.

**Comment by MartinChangCF** [comment]
Sorry for the late reply @jpreese 

I tried the protolint command
```shell
protolint  ./
```
and with `--config_dir_path`

```shell
protolint  --config_dir_path=./ ./protoc
```
they both work properly.

**Comment by jpreese** [comment]
Thanks. I did some investigation on this end as well and am definitely seeing some odd behavior. It _does_ work if the `.protolint.yaml` file is in the same directory as the proto definitions.

I'll do some more digging and see what we can do to get this resolved.

**Comment by jpreese** [comment]
@MartinChangCF this should now be resolved in `v0.3.0` -- could you confirm at your earliest convenience? Thanks again for reaching out 👍

**Comment by MartinChangCF** [comment]
@jpreese Thanks for your updates! It works now 👍

**Comment by jpreese** [comment]
Awesome, glad to hear.
